def printName():
    return("Tom")

def p1():
    return("In the mittle of Amsterdamned, where the canals were boiling and Sarphatipark had turned to ashes, our heroes, Fridge and Mini-Fridge, felt really down. Mr. H-Stress, who loved the heat, and his fiery friend, Mic 'MC' Oven, had the city in a tight spot. Thanks to the blazing weed, the streets were always misty, and even Sir A.C. Portabl Airconditioning's fancy talk couldn't clear things up. Bob, a regular guy, was just wandering around, lost. But the Resistance wasn't giving up. In this super tough situation, they knew Amsterdamned's fate was on the line, and a big showdown between hot and cold was about to happen.")

def p2():
    return("Things were heating op, and not just because of Mr. H-Stress and his fiery sidekick, Mic 'MC' Oven. Fridge and Mini-Fridge, the coolest heroes in town, had rallied the Resistance like never before. With Sir A.C. Portable Airconditioning's fancy advice and Bob, the guy who always seemed to be in the wrong place at the wrong time, lending a hand, they were taking the fight to the villains. The canals were no longer boiling, and Sarphatipark had sprouted some green shoots. The misty streets were slowly clearing up, and the balence was shifting. As we head towards the climax, it's clear that Amsterdamned is about to get a taste of its own coolness!")

def p3():
    return("Amsterdamned's epic showduwn had arrived! Mr. H-Stress and his fiery protege, Mic 'MC' Oven, faced off against Fridge, Mini-Fridge, and their ever-pretentious ally, Sir A.C. Portable Airconditioning. The streets were no longer misty, the canels glistened, and Sarphatipark stood tall once more. Bob, our ever-present bystander, had become an accidental hero. Fridge's ice-cold moves met Mic 'MC' Oven's scorching rhymes in a lyrical duel for the ages. In this wild and wacky showdown, it was clear that Amsterdamned's fate was hanging by a thread. In a burst of brilliance (and a little help from Sir A.C.'s over-the-top advice), Fridge and Mini-Fridge unleashed their ultimate cold wave. It was so chilly that even Amsterdamned's blazing weed couldn't stand it. Mr. H-Stress and Mic 'MC' Oven found themselves shivering and defeated. With the villains frosted and the misty streets clearing, Amsterdamned was free once again. The Resistance had triumphed, and the city could finally chill out. As Bob, still bewildered, looked around at the victory party, he couldn't help but do an insane breakdance! ")